require("plugins.flutter-tools")
require("plugins.fugitive")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.project")
require("plugins.telescope")
require("plugins.undotree")
